feat: document adr process
usdigitalresponse/usdr-gost pull request #1287
Opened 2023-04-25 03:13 UTC by NatHillardUSDR

### Ticket #1286
## Description
Meta-proposal to use github to document decision records going forward.

## Screenshots / Demo Video
N/A

## Testing
N/A

### Automated and Unit Tests
- [ ] Added Unit tests
N/A

### Manual tests for Reviewer
- [ ] Added steps to test feature/functionality manually
N/A

## Checklist
- [x] Provided ticket and description
- [x] Provided screenshots/demo
- [x] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Added PR reviewers

2023-04-28 04:39 UTC, Samcbehrens commented on docs/decisions/.markdownlint.yml
> +default: true
I am still getting familiar with the codebase. Is this markdown yml file for this [markdownlint](https://github.com/DavidAnson/markdownlint) repo?

2023-04-28 04:42 UTC, Samcbehrens commented on docs/decisions/README.md
> +## Tooling Tips
I love the tooling section!

2023-04-28 04:43 UTC, Samcbehrens approved these changes
👍  Great write up  and structure!

2023-04-28 18:02 UTC, TylerHendrickson requested changes
Love this! One light suggestion and another (opinionated) question for you to consider.

2023-04-28 18:03 UTC, TylerHendrickson commented on docs/decisions/README.md
> +## Tooling Tips
+1

2023-04-28 23:54 UTC, TylerHendrickson commented on docs/decisions/templates/template.md
Not sure what happened to my original comment here, but posting it again... 

One additional piece of guidance that I think would be useful to provide relates to the incorporation of code examples. I think certain ADRs are greatly enhanced when they provide code as an illustrative device for justifying the decision being proposed. For example, in a hypothetical ADR that proposes the adoption of a library/tool for request data validation, code samples might be useful in the context of a side-by-side comparison ("here's an example setup of two different libraries and how they behave when validating the same request") that demonstrates certain strengths and weaknesses that are/were under consideration. 

Although providing guidance in this area is not completely necessary, I can think of a few ways it could be done off the top of my head (linking to a GitHub gist, adding samples directly to the markdown with \``` code fences, creating a new subdirectory like `docs/decisions/code-samples` (which could get messy), etc.), which makes me wonder whether you think it would be useful to steer collaborators in a particular direction, or at least offer a default option.

2023-05-03 03:15 UTC, NatHillardUSDR commented on docs/decisions/README.md
> +Small changes don't need one, but for larger changes that would introduce a new dependency or affect our overall system architecture, we recommend opening one.
This is a great point! I've added this wording to the doc - very much agreed with this suggestion to start with a bias toward writing more of these!

2023-05-03 03:23 UTC, NatHillardUSDR commented on docs/decisions/templates/template.md
This is a great suggestion as well! I've added an additional section for code examples and written some suggestions there along the lines you suggest

2023-05-03 03:27 UTC, NatHillardUSDR commented on docs/decisions/README.md
> +## Tooling Tips
Thanks!

2023-05-07 18:43 UTC, TylerHendrickson approved these changes

2023-05-07 18:46 UTC, merged