feat: add user_id and user_properties to GA events
usdigitalresponse/usdr-gost pull request #2467
Opened 2024-01-18 17:19 UTC by sanason

### Ticket #2380
## Description
I can't tell whether we're planning to drop Google Analytics in favor of Datadog RUM but, in case we're not, here's a feature that @jsandlund asked for. Any GA events recorded during a logged in session will now be associated with:

- an organization_name: this is the tenant name
- a team_name: this is the agency name
- a user_id: this is the database id, in accordance with the Google Analytics Terms of Service

> This includes avoiding the use of impermissible personally identifiable information, and providing appropriate notice of your use of identifiers in your Privacy Policy. Your user ID must not contain information that a third party could use to determine a user's identity.

Although I don't know whether we're obeying this part:

> providing appropriate notice of your use of identifiers in your Privacy Policy

In addition to the code changes, I also added Organization and Team as user-scoped custom dimensions in our GA property.

<img width="1342" alt="Screenshot 2024-01-18 at 11 45 59 AM" src="https://github.com/usdigitalresponse/usdr-gost/assets/8216592/1f567b1b-e806-4d76-8dfb-7342412a5fe0">
 

## Screenshots / Demo Video
No user facing changes. For team members exploring our Google Analytics property, the new dimensions should show up in various places. I'm not sure what all of those places are, but here's one example (generated by temporarily enabling GA in my dev environment):

<img width="1296" alt="Screenshot 2024-01-18 at 3 03 12 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/8216592/d96dd7b7-b0d2-4797-879b-6e25b7de9129">

## Testing

### Automated and Unit Tests
- [x] Added Unit tests

### Manual tests for Reviewer
- [ ] Added steps to test feature/functionality manually

## Checklist
- [x] Provided ticket and description
- [x] Provided screenshots/demo
- [ ] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Added PR reviewers

2024-01-18 23:59 UTC, TylerHendrickson requested changes
@sanason No actual changes to request at this time – I need to review our privacy policy to see if everything is square on that end. Just using "Request changes" to prevent merging until I can confirm we're good to go.

2024-01-23 17:34 UTC, TylerHendrickson requested changes
@sanason Overall looks good. As discussed, we'd like to initially stick to using numeric identifiers for user properties rather than the text values. Specifically for this PR, that would be:
- User's agency ID (instead of agency name)
- User's organization ID (instead of organization name)

If you can update things accordingly, then I think this will be good to go!

2024-01-23 19:08 UTC, sanason commented
Updated with requested changes.

2024-01-23 19:14 UTC, TylerHendrickson approved these changes

2024-01-23 19:36 UTC, merged