Exclude .xlsx and .xlsm files from line ending autofixes
usdigitalresponse/usdr-gost pull request #2515
Opened 2024-01-26 18:30 UTC by ajhyndman

### Ticket #<Enter Number Here To Auto-Link>
## Description

Without this change, switching between branches with different versions of t.xlsx or .xlsm files in this repo will cause git to get confused.

Git will attempt to auto-convert anything that looks like a CLRF line ending inside of one of these excel files which could corrupt the file and causes a new uncommitted change to appear unexpectedly.

This change explicitly marks excel files as binary so that they are exempt from this kind of autoconversion.

## Checklist
- [x] Provided ticket and description
- [x] Provided screenshots/demo
- ~Provided testing information~
- ~Provided adequate test coverage for all new code~
- [x] Added PR reviewers

2024-01-26 18:32 UTC, as1729 approved these changes

2024-01-27 01:44 UTC, TylerHendrickson requested changes
@ajhyndman Thanks for this fix! 

One additional request: would you mind moving the `.gitattributes` to the repository root? I'd meant to add it there in the first place; nesting it under `packages/` was an oversight on my part.

2024-01-27 01:44 UTC, TylerHendrickson commented on packages/.gitattributes
> +*.xlsx              binary
Just for completeness...
```suggestion
*.xls               binary
*.xlsm              binary
*.xlsx              binary
```

2024-01-27 22:00 UTC, ajhyndman commented
Sure, good ideas!  Updated

2024-01-29 20:10 UTC, jeffsmohan commented
👋 Just dropping in to say I ran into this with a fresh development environment, and I'm excited for the fix to land! (A fresh checkout of the git repo before I've even touched anything shows 21 files as dirty, which was disconcerting...)

2024-01-29 20:46 UTC, TylerHendrickson approved these changes

2024-01-29 20:54 UTC, merged