feat(grants-collaboration): expose follow for grant
usdigitalresponse/usdr-gost pull request #3397
Opened 2024-08-15 20:35 UTC by greg-adams

### Ticket #3206 
## Description
- Adds api route to expose action for following a grant (`grant_followers`).
- Test changes repeat approach mentioned in #3395 

## Screenshots / Demo Video

## Testing

### Automated and Unit Tests
- [x] Added Unit tests

### Manual tests for Reviewer
- [ ] Added steps to test feature/functionality manually

## Checklist
- [x] Provided ticket and description
- [ ] Provided screenshots/demo
- [ ] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Added PR reviewers

2024-08-21 22:21 UTC, TylerHendrickson requested changes
@greg-adams Overall this is looking good – dropping the same feedback (re skipping `index.js`) I had for the other related PR 

https://github.com/usdigitalresponse/usdr-gost/pull/3395#discussion_r1722002696

2024-08-22 04:23 UTC, greg-adams commented
thanks for catching- updated

2024-08-22 23:20 UTC, TylerHendrickson approved these changes

2024-08-23 16:40 UTC, TylerHendrickson approved these changes

2024-08-23 16:40 UTC, merged