Ms hide forecasted grants
usdigitalresponse/usdr-gost pull request #3456
Opened 2024-09-02 20:12 UTC by masimons

### Ticket #<Enter Number Here To Auto-Link>
## Description

## Screenshots / Demo Video

## Testing

### Automated and Unit Tests
- [ ] Added Unit tests

### Manual tests for Reviewer
- [ ] Added steps to test feature/functionality manually

## Checklist
- [ ] Provided ticket and description
- [ ] Provided screenshots/demo
- [ ] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [ ] Added PR reviewers

2024-09-05 21:33 UTC, TylerHendrickson reviewed
@masimons Confirming that the direction this is headed makes sense to me 👍 

I'll mention that I think it could be useful to have an environment variable control the exclusion of forecasted grants. Due to how we ship and run Docker images, it's not something that we could toggle in a Staging/Prod environment without re-deploying, but 1) it might be helpful for development purposes, and 2) might make it easier to activate once we get to the point where we want to start including forecasted grants in one or both of those environments.

2024-09-16 17:42 UTC, masimons commented
@TylerHendrickson thanks for checking this out, I missed this comment. Out of curiosity, do you have an example off the top of your head where we use an env var in that way? I was looking into how we use feature flags, but it seems that those are scoped to the client side?

2024-09-23 20:40 UTC, TylerHendrickson commented
@masimons re
> Out of curiosity, do you have an example off the top of your head where we use an env var in that way? I was looking into how we use feature flags, but it seems that those are scoped to the client side?

The implementation details for #3060 provide some instructions for implementing an API-side feature flag using a `SHARE_TERMINOLOGY_ENABLED` environment variable (plus a client-side feature flag, which doesn't apply here). This was implemented by PR #3147. 

Fundamentally, this sort of thing would entail the following:
- An env var default value for dev environments, defined in `packages/server/.env.example`.
- Configuring the value for Staging environments as a key/value pair in the [`api_container_environment` input variable](https://github.com/usdigitalresponse/usdr-gost/blob/d27bbe50cefea8e23f5ef8676d9d75653db75242/terraform/staging.tfvars#L74-L77) in `terraform/staging.tfvars`.
- Configuring the value for Production environments via the [same input variable](https://github.com/usdigitalresponse/usdr-gost/blob/d27bbe50cefea8e23f5ef8676d9d75653db75242/terraform/prod.tfvars#L75-L78) in `terraform/prod.tfvars`.

I'd recommend that an environment variable that provides a binary feature flag be evaluated as a string using strict equality, e.g. `my_feature_is_enabled = process.env.MY_FEATURE_ENABLED === 'true'`.

2024-10-11 21:10 UTC, TylerHendrickson requested changes
@masimons I really like how this implementation parameterizes the flag in `src/db/index.js` and allows the caller to decide whether to pull in the toggle from env var or something else. This is looking good overall!

I did notice in local testing that setting `SHOW_FORECASTED_GRANTS=false` in `packages/server/.env` doesn't seem to have the desired effect (I could still see forecasted grants in search results), although when the env var is altogether missing, forecasted grants are hidden like we'd expect. 

I believe this is because the `packages/server/db/index.js` functions are expecting a true boolean value (or else `undefined`, so that the arg default of `false` in the function signature is used), but when a value is provided from `process.env.SHOW_FORECASTED_GRANTS`, it's a string rather than a boolean, and `!"false"` is evaluating to `true`. I think the simplest way to resolve this is to have callers explicitly check whether `process.env.SHOW_FORECASTED_GRANTS === "true"`, which I provided in a comment suggestion.

2024-10-16 20:40 UTC, lsr-explore commented
> @masimons I really like how this implementation parameterizes the flag in `src/db/index.js` and allows the caller to decide whether to pull in the toggle from env var or something else. This is looking good overall!
> 
> I did notice in local testing that setting `SHOW_FORECASTED_GRANTS=false` in `packages/server/.env` doesn't seem to have the desired effect (I could still see forecasted grants in search results), although when the env var is altogether missing, forecasted grants are hidden like we'd expect.
> 
> I believe this is because the `packages/server/db/index.js` functions are expecting a true boolean value (or else `undefined`, so that the arg default of `false` in the function signature is used), but when a value is provided from `process.env.SHOW_FORECASTED_GRANTS`, it's a string rather than a boolean, and `!"false"` is evaluating to `true`. I think the simplest way to resolve this is to have callers explicitly check whether `process.env.SHOW_FORECASTED_GRANTS === "true"`, which I provided in a comment suggestion.

@TylerHendrickson , @masimons - I've accepted Ty's changes - this should be ready for review

2024-10-21 20:20 UTC, TylerHendrickson requested changes
@lsr-explore Thanks for the updates. I think we need the strict `=== 'true'` comparision for all usages of the environment variable, so I added a few additional comment suggestions to address those as well.

2024-10-21 20:20 UTC, TylerHendrickson commented on packages/server/src/lib/email.js
> +        const grant = await db.getGrant({ grantId, showForecastedGrants: process.env.SHOW_FORECASTED_GRANTS });
```suggestion
        const grant = await db.getGrant({ grantId, showForecastedGrants: process.env.SHOW_FORECASTED_GRANTS === 'true' });
```

2024-10-21 20:20 UTC, TylerHendrickson commented on packages/server/src/routes/grants.js
> +        showForecastedGrants: process.env.SHOW_FORECASTED_GRANTS,
```suggestion
        showForecastedGrants: process.env.SHOW_FORECASTED_GRANTS === 'true',
```

2024-10-21 20:20 UTC, TylerHendrickson commented on packages/server/src/routes/grants.js
> +        process.env.SHOW_FORECASTED_GRANTS,
```suggestion
        process.env.SHOW_FORECASTED_GRANTS === 'true',
```

2024-10-21 20:20 UTC, TylerHendrickson commented on packages/server/src/routes/grants.js
> +        process.env.SHOW_FORECASTED_GRANTS,
```suggestion
        process.env.SHOW_FORECASTED_GRANTS === 'true',
```

2024-10-22 16:05 UTC, lsr-explore commented
> @lsr-explore Thanks for the updates. I think we need the strict `=== 'true'` comparison for all usages of the environment variable, so I added a few additional comment suggestions to address those as well. I _think_ that I covered all of them, but feel free to double check me on that 🙂

Sorry that I missed this @TylerHendrickson .  I applied the changes and did another sanity check of the code.  I noticed a couple additional places where the flag needed to be sent and added a commit.

I noticed that the db.getGrantsInterested didn't have this check.   This would only be an issue if we needed to turn off grants after enabling it and user had clicked follow.   

Do you think we need the check on getGrantsInterested?

2024-10-24 06:12 UTC, masimons commented
> 
> I noticed that the db.getGrantsInterested didn't have this check. This would only be an issue if we needed to turn off grants after enabling it and user had clicked follow.
> 
> Do you think we need the check on getGrantsInterested?


That's a fair point - I don't know if that particular case came up when we were thinking about this

2025-04-01 17:16 UTC, closed without merging