feat: add API to retrieve grant notes for specific user via Finder API
usdigitalresponse/usdr-gost pull request #3471
Opened 2024-09-05 23:15 UTC by sushilrajeeva

### Ticket #3426 

## Description
This PR implements the ability to retrieve notes for a specific user and grant via the Finder API, addressing the requirements outlined in the issue #3426 

Changes include :
  - Implemented `getOrganizationNotesForGrantByUser()` function in `grantsCollaboration/notes.js`
  - Renamed `getOrganizationNotesForGrant()` to `getCurrentNoteRevisions()` and updated signature
  - Made conditional `WHERE` clause for `grantId` and `userId` in `getCurrentNoteRevisions()`
  - Created API route `GET /:grantId/notes/user/:userId` in `grants.js` for fetching user-specific grant notes
  - Added validation for `afterRevision` and `limit` query parameters in the new API
  - Ensured results are paginated and ordered by `created_at` in descending order
  - Added necessary imports/exports in `grantsCollaboration/index.js`

Fixes #3426 

## Screenshots / Demo Video
N/A
## Testing

### Automated and Unit Tests
- [ ] Added Unit tests

### Manual tests for Reviewer
- [ ] Added steps to test feature/functionality manually

## Checklist
- [X] Provided ticket and description
- [ ] Provided screenshots/demo
- [ ] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [X] Added PR reviewers

2024-09-06 23:37 UTC, greg-adams commented
@sushilrajeeva is it possible to add test coverage for this new route?

2024-09-11 18:15 UTC, TylerHendrickson approved these changes
@sushilrajeeva Looks good!

2024-09-11 18:17 UTC, TylerHendrickson requested changes
@sushilrajeeva Apologies for the premature approval – I missed checking the unit tests. Agree with @greg-adams' [comment](https://github.com/usdigitalresponse/usdr-gost/pull/3471#issuecomment-2334940744) that it would be good for this new route to have test coverage.

2024-09-18 16:47 UTC, TylerHendrickson commented on packages/server/src/lib/grantsCollaboration/notes.js
> +    return getCurrentNoteRevisions(knex, { grantId, userId }, { afterRevision, limit });
Per https://github.com/usdigitalresponse/usdr-gost/issues/3426#issuecomment-2358790420:
```suggestion
    return getCurrentNoteRevisions(knex, { grantId, organizationId, userId }, { afterRevision, limit });
```

2024-09-24 16:58 UTC, TylerHendrickson approved these changes
As discussed in today's meeting, I think this is okay to merge given the lib tests are present. We will create a separate issue to address missing tests for `packages/server/routes/grants.js`.

2024-09-24 16:58 UTC, merged