791: add missing self parent agency error
usdigitalresponse/usdr-gost pull request #922
Opened 2023-02-05 16:26 UTC by chrisxkeith

### Ticket #
#791
### Description
See ticket
### Screenshots / Demo Video
![image](https://user-images.githubusercontent.com/3921494/216831536-0fcdd16c-c8b9-4cb4-bc79-bec12cc16514.png)
### Testing
Manual
### Checklist
- [x] Provided ticket and description
- [x] Your PR title contains the ISSUE ticket number e.g "86: ..."
- [x] Provided screenshots/demo
- [x] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Run automated tests (docker compose exec app yarn test)
- [x] Added PR reviewers
- [ ] Ensure at least 1 review before merging

2023-02-06 15:58 UTC, TylerHendrickson requested changes
Just a small spelling nit, otherwise looks good to me!

2023-02-06 15:58 UTC, TylerHendrickson commented on packages/client/src/components/Modals/EditAgency.vue
> +          await this.$bvModal.msgBoxOk('Agency can not be its own parent.');
Nit: "cannot" instead of "can not"

2023-02-06 18:03 UTC, chrisxkeith commented
Done! Thanks.

2023-02-07 17:07 UTC, TylerHendrickson approved these changes

2023-02-07 17:21 UTC, merged